### ISSUE TITLE
import error for moviepy

### ISSUE THREAD

**Issue by yassermabdallah** [udacity/CarND-Term1-Starter-Kit#104]
Hi guys

When I run the following command I get an error, it's seems something is missing in the environmental installation. Could you help me to solve this?

# Import everything needed to edit/save/watch video clips
import imageio
imageio.plugins.ffmpeg.download()

from moviepy.editor import VideoFileClip
from IPython.display import HTML

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-31054135068b> in <module>()
      3 #imageio.plugins.ffmpeg.download()
      4 
----> 5 from moviepy.editor import VideoFileClip
      6 from IPython.display import HTML

~/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/editor.py in <module>()
     29 from .video.io.VideoFileClip import VideoFileClip
     30 from .video.io.ImageSequenceClip import ImageSequenceClip
---> 31 from .video.io.downloader import download_webfile
     32 from .video.VideoClip import VideoClip, ImageClip, ColorClip, TextClip
     33 from .video.compositing.CompositeVideoClip import CompositeVideoClip, clips_array

~/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/moviepy/video/io/downloader.py in <module>()
      5 import os
      6 
----> 7 import requests
      8 
      9 from moviepy.tools import subprocess_call

ImportError: No module named 'requests'

**Comment by mvirgo** [comment]
Hi there - please use `pip install requests` from within the activated conda environment. For some reason `requests` is not always being downloaded as part of the environment installation.
