### ISSUE TITLE
a link doesn't work

### ISSUE THREAD

**Issue by SeokLeeUS** [udacity/CarND-Term1-Starter-Kit#109]
https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md

![image](https://user-images.githubusercontent.com/44729645/51754662-ddc8a280-208a-11e9-8582-729734636e89.png)

**Comment by mvirgo** [comment]
Nice catch, looks like they changed their website to conda.io. Fixed.
