### ISSUE TITLE
tensorflow doesn't find right version on the requirement.txt

### ISSUE THREAD

**Issue by SeokLeeUS** [udacity/CarND-Term1-Starter-Kit#110]
environment.yml shows required tensorflow is 1.3.0, but it threw the error as shown below (window environment):

![image](https://user-images.githubusercontent.com/44729645/51756676-92fd5980-208f-11e9-8bbb-d92760cb7f68.png)

**Comment by mvirgo** [comment]
Can you try to install it from https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow-1.3.0-cp35-cp35m-win_amd64.whl instead? I.e. replace the `tensorflow=1.3.0` line with that.

**Comment by mvirgo** [comment]
No further comments in two months; closing.
