### ISSUE TITLE
32 bit install?

### ISSUE THREAD

**Issue by SeokLeeUS** [udacity/CarND-Term1-Starter-Kit#111]
I think it should be with 64 bit only to work with python/ tensor flow....

![image](https://user-images.githubusercontent.com/44729645/53112228-c905f000-350c-11e9-8201-4ed6bb9759c4.png)

https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md

**Comment by mvirgo** [comment]
There are not official TensorFlow installs for 32-bit systems, but there are ways to build from source and still use. So, you wouldn't be able to use TensorFlow directly from the starter kit, but you can still use most of the other libraries.

**Comment by mvirgo** [comment]
No further comments in a month; closing.
