### ISSUE TITLE
do I install miniconda ?

### ISSUE THREAD

**Issue by jisu5619** [udacity/CarND-Term1-Starter-Kit#124]
I have some confuse.

I already  have anaconda . then I have to install miniconda on windows10 environment for installing carnd-term1

Do i install miniconda ?

**Comment by EyeEyeloving** [comment]
I think Ananconda can work as well as Miniconda.

**Comment by UAnjali** [comment]
Hi @jisu5619 
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime in and new students can also learn from the discussion thread. 
Thank you
