### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by kvasnyj** [udacity/CarND-Term1-Starter-Kit#17]
PS SDC\Repo\CarND-Term1-Starter-Kit> docker build -t carnd-term1 .

An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/build?buildargs=%7B%7D&cgroupparen
t=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=
1&shmsize=0&t=carnd-term1&ulimits=null: open //./pipe/docker_engine: The system cannot find the file specified.

**Comment by domluna** [comment]
Not sure what the issue but try pulling the image directly from Docker Hub:

`docker pull udacity/carnd-term1-starter-kit`
