### ISSUE TITLE
build is successful but can't start container

### ISSUE THREAD

**Issue by anguillanneuf** [udacity/CarND-Term1-Starter-Kit#19]
![20161128g](https://cloud.githubusercontent.com/assets/9518298/20689231/321aad08-b592-11e6-9edd-49d5f0b4da34.PNG)

**Comment by domluna** [comment]
I think this might because of pwd. On Windows \`pwd\` doesn't work. `${pwd}` seems to work though.

**Comment by domluna** [comment]
the README was updated to talk about this and other stuff

**Comment by anguillanneuf** [comment]
![20161129](https://cloud.githubusercontent.com/assets/9518298/20716693/16e2cc70-b621-11e6-8e8f-96a0af5ec0fe.PNG)

@domluna Thank you! I tried again this morning. **`$(pwd)`** worked for me perfectly. And thanks for the update in README too!
