### ISSUE TITLE
windows command specifically `pwd`

### ISSUE THREAD

**Issue by giladgressel** [udacity/CarND-Term1-Starter-Kit#22]
@domluna 

this section in the readme.md

>If you're on Windows:
`docker run -it --rm -p 8888:8888 -v ${pwd}:/src udacity/carnd-term1-starer-kit`

Actually I think the `{pwd}` is windows 10 specific.  It's docker for windows.  Windows <10 is docker toolbox, which has a bash terminal afaik

so that command should only be for win 10.  The other one for other versions...

**Comment by domluna** [comment]
So \`pwd\` works on all Windows except 10?

**Comment by giladgressel** [comment]
I _think_ so, you should double check.  it's my understanding that windows for docker runs in cmd, which doens't have bash commands so you need {}  but the other windows get docker toolbox, which come with a bash, that accepts the `pwd`

**Comment by domluna** [comment]
https://carnd-udacity.atlassian.net/wiki/questions/18451525/answers/18454088 Looks like this guy used the backticks. He's on Windows 8.1.
