### ISSUE TITLE
Error on docker build Ubuntu 14.04

### ISSUE THREAD

**Issue by AndreaIncertiDelmonte** [udacity/CarND-Term1-Starter-Kit#43]
Hi,
I'm trying to build the Dockerfile.cpu on my laptop with Ubuntu 14.04 and I get the following error: 
`CondaError: OSError(18, 'Invalid cross-device link')` on the command `RUN conda env create -f=environment.yml --name carnd-term1`.

My `docker version`:
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:26:30 2017
 OS/Arch:      linux/amd64

**Comment by JGuillaumin** [comment]
I have the same problem ..

**Comment by domluna** [comment]
@AndreaIncertiDelmonte what was the initial command you ran?

**Comment by AndreaIncertiDelmonte** [comment]
Hi Dom!

I run `docker build -f Dockerfile.cpu -t myuser/myimage:cpu .`.
The basic docker command to build images.

Thanks
Andrea

**Comment by domluna** [comment]
I'm able to reproduce it. Seems to be an issue with creating an environment during a Docker build with conda 4.3.0. https://github.com/conda/conda/issues/4309. I'll see about reverting back to 4.2.x.

**Comment by domluna** [comment]
@AndreaIncertiDelmonte I updated the file, works on my end now. The build on Docker hub is failing though ... not sure why.

**Comment by JGuillaumin** [comment]
Thank you very much ! It works for me !

**Comment by AndreaIncertiDelmonte** [comment]
Hi @domluna,
your fix works also for me :) 
Tnks
Andrea
