### ISSUE TITLE
instructions to activate carnd-term1 on windows

### ISSUE THREAD

**Issue by SherylHohman** [udacity/CarND-Term1-Starter-Kit#51]
I'm on Windows 7 Pro:

Instructions for Windows say that to activate, one must type:
`activate carnd-term1`   

However, this was the response:   
`i Term1 $ activate carnd-term1`
`Error: activate must be sourced. Run 'source activate envname'
instead of 'activate envname'.`   

So I did as it said (shich is the same command as for non-Windows users), and this was the response:
`i Term1 $ source activate carnd-term1`   
`(carnd-term1) i Term1 $`

Note: I haven't gotten any further than this, so I dunno if anything else works.  
But it looks to me that the same command as for non-Windows users,   
was needed to activate the anaconda environment on my Windows 7 Pro machine.

**Comment by domluna** [comment]
@SherylHohman On Windows it depends what shell you use whether you have to type `source` or not. Most shells you do not in my experience, I'm not sure if this is different on Windows 7. In any case the output you received from running `source activate carnd-term1` looks to be correct, that is, `(carnd-term1)` being prefixed to the command prompt. Just run whichever works :-)

**Comment by SherylHohman** [comment]
What I found is that when I run "cmd" the command prompt shell As Administrator, I do NOT type in "source", as you say.

However when I use git bash, or run "cmd" normally, I Do need "source".

So perhaps indicating that windows users might need to use one command, or other other, is more accurate.

**Comment by domluna** [comment]
I've updated the instructions #56 to indicate this.

**Comment by TanayAarush** [comment]
```

USER1234@Computer32 MINGW64 ~/CarND-Term1-Starter-Kit-Test (master)
$ source activate carnd-term1
bash: activate: No such file or directory
```


Even I tried 

`source activate CarND-Term1-Starter-Kit-Test`

from git-bash.

I am writing the above command from git-bash. But I get the error,
`bash: activate: No such file or directory`


Even I ran activate carnd-term1 from 'cmd' still the same error.  Please help.
