### ISSUE TITLE
Use newer version of nvidia-docker (Docker 1.13.0 is out)

### ISSUE THREAD

**Issue by boxmein** [udacity/CarND-Term1-Starter-Kit#53]
The "Install nvidia-docker" line should be replaced like this:

    wget -P /tmp https://github.com/NVIDIA/nvidia-docker/releases/download/v1.0.0/nvidia-docker_1.0.0-1_amd64.deb

See https://github.com/NVIDIA/nvidia-docker/issues/294

**Comment by domluna** [comment]
Thanks @boxmein, I've changed it so it links directly to the nvidia-docker README for those instructions.
