### ISSUE TITLE
Could not find a version that satisfies the requirement tensorflow

### ISSUE THREAD

**Issue by jgilbert42** [udacity/CarND-Term1-Starter-Kit#61]
I got this error when I tried to re-create my conda environment on Mac OS.  Caused by tensorflow 1.0 release?

Moving tensorflow out of the pip section and using tensorflow=0.12.1 allowed me to create the environment and run CarND-LeNet-Lab/LeNet-Lab-Solution.ipynb.

**Comment by domluna** [comment]
Set the TF version in environment.yml to 0.12.1. AFAIK most of the content might not support 1.0 yet anyway.

**Comment by davidhungh** [comment]
Please advice! 
I still have problem with this issue. 
I first put tensorflow == 0.12.1 in the pip section. It did not work
I delete the line with tensorflow, finished with the creation of the env. Then using pip install tensorflow == 0.12.1 ---> still did not work

What do you mean by moving tensorflow out of the pip section. Inside the env. file what should I write? pip install tensorflow == 0.12.1?

**Comment by davidhungh** [comment]
Is it something with Python version. My version is python==3.5.2

**Comment by davidhungh** [comment]
Ok! I got it now. I move tensorflow outside the pip section as following: 
- tensorflow==0.12.1

**Comment by domluna** [comment]
I was just referring to this file https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/environment.yml. Previously the TensorFlow wasn't pinned at a specific version so it would download the latest one (v1.0). Now it'll download v0.12.1 instead.

**Comment by davidhungh** [comment]
It is working now for me as my environment.yml is as following:

name: carnd-term1
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - imageio
    - tensorflow==0.12.1
    - pip:
        - moviepy
        - git+https://github.com/fchollet/keras.git
