### ISSUE TITLE
NoPackagesFoundError: pyqt 4.11.3 for Miniconda3 4.2.12

### ISSUE THREAD

**Issue by Sleepingkoala** [udacity/CarND-Term1-Starter-Kit#67]
Hi guys. 
Since I always met troubles installing Miniconda3 4.3.13 and 4.3.11- Windows-x86-64(can not run .exe smoothly), I have downloaded the Miniconda3 4.2.12 version and finished the installation successfully. While following the instruction in readme.txt and creating the environment carnd-term1 with environment.yml, I met the error as follows:

**NoPackagesFoundError: Package missing in current win-64 channels:
 - pyqt 4.11.3***
![error](https://cloud.githubusercontent.com/assets/4024858/23492932/b5a42bc8-ff42-11e6-9511-2c421744dee3.PNG)

the attached figure will show exact status of this error.
Could anyone help me? I have been stuck here for this whole day, which delayed my assignment badly. Please help!

**Comment by Sleepingkoala** [comment]
@dsilver829

**Comment by akshaybabloo** [comment]
Have you tried Anaconda?

**Comment by mvirgo** [comment]
No further discussions in over a year; closing out.
