### ISSUE TITLE
undefined symbol: cudnnCreate

### ISSUE THREAD

**Issue by stoicio** [udacity/CarND-Term1-Starter-Kit#76]
I tried building an image from the Dockerfile.gpu file and the build process succeeded without any errors.
However when I try to run some of the tensor flow scripts the scripts fails with the following error

`F tensorflow/stream_executor/cuda/cuda_dnn.cc:221] Check failed: s.ok() could not find cudnnCreate in cudnn DSO; dlerror: /root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: cudnnCreate
Aborted (core dumped)`

**Comment by stoicio** [comment]
I have been able to work around this temporarily by using the offlicial tensorflow image as the base image instead of using nvidia's docker image.
I replaced the `# FROM nvidia/cuda:8.0-cudnn5-runtime-ubuntu16.04` with `FROM gcr.io/tensorflow/tensorflow:latest-gpu-py3`

**Comment by mvirgo** [comment]
Sounds like you found a fix, so closing out.
