### ISSUE TITLE
The instalation abort with error:PaddingError: Placeholder of length '32' too short in package conda-forge

### ISSUE THREAD

**Issue by flamoedo** [udacity/CarND-Term1-Starter-Kit#77]
The instalation abort with the following error:

PaddingError: Placeholder of length '32' too short in package conda-forge::hdf5-1.8.17-vc14_11.
The package must be rebuilt with conda-build > 2.0.

**Comment by rohts-patil** [comment]
This is the solution:
https://github.com/conda-forge/hdf5-feedstock/issues/41#issuecomment-250928084

**Comment by mvirgo** [comment]
Looks like Rohit solved this above.
