### ISSUE TITLE
‘git' is not recogonized

### ISSUE THREAD

**Issue by siyingliu1112** [udacity/CarND-Term1-Starter-Kit#78]
Hi,
I installed Anaconda environment miniconda v 4.3.13, but when I open the Anaconda prompt and run the first line "git clone https://github.com/udacity/CarND-Term1-Starter-Kit.git ", it says: 'git' is not recognized as an internal or external command, operable program or batch file.
Could someone help me with this issue?
Thanks!

**Comment by domluna** [comment]
@siyingliu1112 This means you don't have git installed or it's not in your PATH.

https://git-scm.com/downloads
