### ISSUE TITLE
conda env create -f environment.yml doesn't work

### ISSUE THREAD

**Issue by JSRGFJZ** [udacity/CarND-Term1-Starter-Kit#82]
Hi,"conda env create -f environment.yml" reallly doesn't work, I just googled some, there is one post writing "conda env create -f=environment.yml", well, It is downloading  something now, why is that?

**Comment by domluna** [comment]
@JSRGFJZ They should be equivalent I just ran the former and it worked. Was there an error when you ran it or did it just time out? It's possible Anaconda didn't respond.

**Comment by JSRGFJZ** [comment]
ok, I tryied, it alwayes showed that CondaHTTPError, does it mean that my network is so bad?

**Comment by domluna** [comment]
yeah that generally means the connection is not good. The connection shouldn't all of sudden get significantly better by typing -f=environment.yml instead of -f environment.yml though

**Comment by mvirgo** [comment]
Sounds like it was just a network issue; closing out.
