### ISSUE TITLE
No test file test.ipynb

### ISSUE THREAD

**Issue by vikasmalik22** [udacity/CarND-Term1-Starter-Kit#84]
Hi. 
The root folder doesn't contain any test.ipynb to test and make sure the installed packages are working properly as mentioned in the course 18. Run Some Code.

**Comment by tomarharsh14** [comment]
Still having this issue? Works fine for me. Did you read the Note carefully? 
`
# NOTE: This is DIFFERENT from  https://github.com/udacity/CarND-Term1-Starter-Kit.git
git clone https://github.com/udacity/CarND-Term1-Starter-Kit-Test.git
cd CarND-Term1-Starter-Kit-Test
`

Starter-Kit and Starter-Kit-Test are different repositories.

**Comment by mvirgo** [comment]
As noted above, that's a different repository; closing out.
