### ISSUE TITLE
Creating environment hangs after jupyter-1.0.0 package expansion

### ISSUE THREAD

**Issue by derekdominoes** [udacity/CarND-Term1-Starter-Kit#89]
Running Winodws 10 Pro
Command line in Anaconda Prompt is :  conda env create -f environment.yml
The meta.yaml file was renamed.
Tried this four times now and if hang here every time.
The current Docker CE edition does not start (fatal error on starting) on my system so I can't switch to that

![image](https://user-images.githubusercontent.com/16954767/33682567-8bcc515a-da8d-11e7-96e7-eb02e47896cd.png)

**Comment by mvirgo** [comment]
Sounds like there was an update to conda that has fixed this:

```
conda config --add channels conda-canary
conda update conda
```
