### ISSUE TITLE
Create Environment fails

### ISSUE THREAD

**Issue by bmota75** [udacity/CarND-Term1-Starter-Kit#91]
![image](https://user-images.githubusercontent.com/34128598/35144460-e1ee44a0-fd04-11e7-9131-0cb42e853d2e.png)

I get this error while trying to create carnd-term1. I tryind multiple times with the same result.
Help highly appreciated.

**Comment by mvirgo** [comment]
Hi there! A previous student had this issue as well, where it was noted it had to due with the network speed on the student's end. Have you had any luck with it yet?

**Comment by mvirgo** [comment]
No further comments; closing.
