### ISSUE TITLE
error creating conda environment with gpu installation on windows

### ISSUE THREAD

**Issue by Sahil-24** [udacity/CarND-Term1-Starter-Kit#94]
when attempting to execute:
`conda env create -f environment-gpu.yml`
on a windows machine the following error exists:
![image](https://user-images.githubusercontent.com/28517791/37702603-2e6d5c7c-2d47-11e8-8abb-9c8676bb7c54.png)

it looks like the `environment-gpu.yml` is pointing to the path of the linux gpu installation of tensorflow not the windows equivalent?

**Comment by swarmt** [comment]
Hey Mate,

The link from PyPi installs. I am going to try using it. It is a newer version of tensorflow though.
https://pypi.python.org/packages/5b/a8/8cb5d416f7bebb9f470a3a76b85d553385a0006dabf4589a8a41af23a8f1/tensorflow-1.7.0-cp35-cp35m-win_amd64.whl#md5=3ce776d4f5717a9e27f6e0e19407012b

**Comment by kambliketan** [comment]
having same issue. Were you able to get it installed successfully.

**Comment by mvirgo** [comment]
No recent comments, but also wanted to note that this is the linux version of the file (note the `linux_x86_64` part of the file name) - you'll want to update this to the relevant Windows file.
