### ISSUE TITLE
conda enviroment create missing moviepy

### ISSUE THREAD

**Issue by Jessica001cheng** [udacity/CarND-Term1-Starter-Kit#95]
Hi, when i use command ""conda env create -f environment.yml" to install packages, below error report: "

 "Collecting moviepy (from -r C:\Users\UIDQ6035\Documents\self driving\Term1\CarND -Term1-Starter-Kit-master\condaenv.vu4d2e.requirements.txt (line 1)) Could not find a version that satisfies the requirement moviepy (from -r C:\Us ers\UIDQ6035\Documents\self driving\Term1\CarND-Term1-Starter-Kit-master\condaen v.vu4d2e.requirements.txt (line 1)) (from versions: ) No matching distribution found for moviepy (from -r C:\Users\UIDQ6035\Documents\ self driving\Term1\CarND-Term1-Starter-Kit-master\condaenv.vu4d2e.requirements.t xt (line 1))

CondaValueError: pip returned an error "

I use Windows7 and behind proxy.

**Comment by Jessica001cheng** [comment]
can any one reply this issue? it is now blocking my conda installation.

**Comment by mvirgo** [comment]
Closing out based on Issue age & no further comments; you can also try removing the line, finishing installing the environment, activate that particular environment, then run `pip install moviepy` again.
