### ISSUE TITLE
Faild to build docker image using Dockerfile

### ISSUE THREAD

**Issue by atinfinity** [udacity/CarND-Term1-Starter-Kit#99]
I tried to build docker image using Dockerfile of CarND-Term1-Starter-Kit.
<https://github.com/udacity/CarND-Term1-Starter-Kit>

But, I could not build docker image. Please give me some advice.

### System information(host PC)
- Ubuntu 16.04 64bit
- nvidia-387
- nvidia-docker2

#### CPU
```shell
$ git clone https://github.com/udacity/CarND-Term1-Starter-Kit.git
$ cd CarND-Term1-Starter-Kit
$ docker build -t udacity/carnd-term1-starter-kit -f Dockerfile.cpu .
```
#### GPU
```shell
$ git clone https://github.com/udacity/CarND-Term1-Starter-Kit.git
$ cd CarND-Term1-Starter-Kit
$ docker build -t udacity/carnd-term1-starter-kit -f Dockerfile.gpu .
```
### Error message
The following message was displayed.

```
Traceback (most recent call last):                                       |  14%
  File "/root/miniconda3/envs/carnd-term1/bin/jupyter-nbextension", line 7, in <module>
    from notebook.nbextensions import main
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/root/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ImportError: No module named 'jupyter_core'
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

```

**Comment by Tsuihao** [comment]
I  faced the same issue, I think the reason is `conda` outage.
Add `RUN conda update -n base conda -y  ` in the Dockerfile.cpu / Dockerfile.gpu 
As shown in the following here: https://github.com/Tsuihao/CarND-Term1-Starter-Kit/commit/0687915789f41e4040fe6d9c22f4c66e43a8e766

And it works!

**Comment by mvirgo** [comment]
We've since updated the conda version in the Dockerfile to avoid this issue, although the solution above should also work.
